---
- hosts: localhost
  connection: local
  gather_facts: false
  vars_files:
    - vars.yml
  ignore_errors: true
  tasks:
    - name: Run init setup
      include_role:
        name: setup
      when: runsetup
      
    - name: Run idp role
      include_role:
        name: idp
      when: runidp

    - name: Run audit role
      include_role:
        name: audit
      when: runaudit

    - name: Run ssl role
      include_role:
        name: ssl
      when: runssl

# create a task for waiting for ssl to complete before sending out the notifcation
    - name: Run notification role
      include_role:
        name: notification
      when: runnotification