---
- hosts: localhost
  connection: local
  gather_facts: false
  vars_files:
    - vars.yml
  ignore_errors: true
  tasks:
    - name: Run notification role
      include_role:
        name: notification
      when: runnotification

    - name: Run idp role
      include_role:
        name: idp
      when: runidp

    - name: Run ssl role
      include_role:
        name: ssl
      when: runssl

    - name: Run audit role
      include_role:
        name: audit
      when: runaudit
