---
# tasks file for setup
- name: Get Partner Lab ClusterDeployment
  kubernetes.core.k8s_info:
    api_key: "{{ k8s_auth_clusterdeployment_reader_key }}"
    api_version: hive.openshift.io/v1
    host: "{{ k8s_auth_admin_host }}"
    kind: ClusterDeployment
    namespace: "{{ generated_name }}"
    name: "{{ generated_name }}"
    persist_config: false
    validate_certs: false
  register: partner_lab_cluster_deployment

- name: Get Partner Lab Kubeconfig
  kubernetes.core.k8s_info:
    api_key: "{{ k8s_auth_secret_reader_key }}"
    api_version: v1
    host: "{{ k8s_auth_admin_host }}"
    kind: Secret
    name: "{{ partner_lab_cluster_deployment.resources[0].spec.clusterMetadata.adminKubeconfigSecretRef.name }}"
    namespace: "{{ generated_name }}"
    persist_config: false
    validate_certs: false
  register: partner_lab_kubeconfig

- name: Create local kubeconfig
  ansible.builtin.copy:
    content: "{{ partner_lab_kubeconfig.resources[0].data.kubeconfig|b64decode }}"
    dest: "/tmp/kubeconfig"
    mode: '0600'